### ISSUE TITLE
feat(security): use `SFTP` instead of `FTP`

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/TESK#175]
Description:
Currently on main branch we are ignore a bandit error which is caused due due to use of FPT modules and its related functions. To keep data transfer secure and encrypted it would be recommended to use SFTP than FTP.

**Comment by uniqueg** [comment]
As mentioned earlier, we may still need to continue supporting FTP. But before anything about any of that, we probably need to think about designing a sytem for truly pluggable support of different filers. I guess that should already go a long way. Still might not fix that Bandit error (if we decide to keep regular FTP, we probably need to bite that bullet), but at least it would make the code base saner/more maintainable and also make it easier to drop support for a given filer.

**Comment by uniqueg** [comment]
Very good, thanks a lot. Attached "wontfix" and will close this now, to be revisited later.

To summarize:
- In the mid-term, it probably makes sense to refactor the filer code (opened #179 to discuss this)
- Once we have a better setup for adding new filers, we can implement SFTP when somebody asks for it
- We can discuss removing FTP at a later point (I don't it is necessarily tied to the question of whether or not we should SFTP)
