### ISSUE TITLE
GridFTP input/output support

### ISSUE THREAD

**Issue by erikvdbergh** [elixir-cloud-aai/TESK#19]
Filer image needs to support gridftp, probably using globus python SDK: https://globus-sdk-python.readthedocs.io/en/latest/

**Comment by psafont** [comment]
@JinnyChien may be able to help us, she is also using gridftp and globus in her service

**Comment by JinnyChien** [comment]
Yes, I am implementing Globus in RDSDS service. Current RDSDS supports GridFTP and FTS3 to transfer files.

**Comment by psafont** [comment]
There are no instructions on what to test or how to test this @susheel

**Comment by susheel** [comment]
**Test Setup**
1. Build [multi-filer](https://github.com/EMBL-EBI-TSI/multi-filer) container
2. Obtain ELIXIR Proxy Grid Certificate from [ELIXIR CILogin](https://elixir-cilogon-mp.grid.cesnet.cz/vo-portal/)
3. Save certificates as usercert.pem and private key as userkey.pem in a local directory

**Test Script**
1. Create test.json file 
```
{
    "inputs": [
      {
        "name": "input1",
        "description": "Example",
        "url": "gsiftp://hh-gridftp-2.ebi.ac.uk/gridftp/1000g/CHANGELOG",
        "path": "/tmp/CHANGELOG",
        "type": "FILE"
      }
    ]
}
```
2. Run multi-filer
```
docker run -it <multi-filer CONTAINER> \
-v $(PWD):/globus/
-e SRC_GSIFTP_USER_CERT='/globus/usercert.pem' \
-e SRC_GSIFTP_USER_KEY='/globus/userkey.pem' \
inputs test.json
```
