### ISSUE TITLE
Clean up old jobs (> 30 days) via Kubernetes CronJob

### ISSUE THREAD

**Issue by susheel** [elixir-cloud-aai/TESK#36]

**Comment by kfox1111** [comment]
+1

**Comment by kfox1111** [comment]
And possibly an api to allow a task to be deleted that is known to be done.

**Comment by kfox1111** [comment]
Cleanup can almost be done by:
task=task-d4f5334e
kubectl delete job $task
kubectl delete job -l taskmaster-name=$task

But not all jobs are marked with taskmaster-name. the input/output jobs in  particular.
